import { Metadata } from 'next';
import './globals.css';
import { ClientLayout } from './client.layout';
import themes from 'public/themes/themes-config.json';

export const metadata: Metadata = {
  title: 'Wavemaker App',
  description: 'An nextjs app generated by wavemaker studio',
  icons: {
    icon: '/favicon.png',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch config data
  const lang = 'en';
  console.log("NEXT_PUBLIC_SERVER_PATH from layout--->", process.env.NEXT_PUBLIC_SERVER_PATH)
  
  const configs = {
    appConfig: {
      url: process.env.NEXT_PUBLIC_SERVER_PATH,
      preferences: {},
      appProperties: {},
    },
    appVariables: {},
  };

  return (
    <html lang={lang}>
      <head>
        <link
          rel="stylesheet"
          href={`/themes/${themes.activeTheme}/style.css`}
          precedence="default"
        />
      </head>
      <body className={`wm-app wm-theme-${themes.activeTheme}`}>
        <ClientLayout configs={configs}>{children}</ClientLayout>
      </body>
    </html>
  );
}
